name: Build and Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@reenedgesolutions"
      - name: Debug - Check token and env variables
        run: |
          echo "NODE_AUTH_TOKEN is set: ${{ secrets.GH_TOKEN }}"
          echo "Debugging the environment variables:"
          printenv
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@reenedgesolutions"
      - name: Debug - Check token and env variables
        run: |
          echo "NODE_AUTH_TOKEN is set: ${{ secrets.GH_TOKEN }}"
          echo "Debugging the environment variables:"
          printenv
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm run build:prod

  publish:
    needs: [lint, build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@reenedgesolutions"
      - name: Debug - Check token and env variables
        run: |
          echo "NODE_AUTH_TOKEN is set: ${{ secrets.GH_TOKEN }}"
          echo "Debugging the environment variables:"
          printenv
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
